#!/usr/bin/perl
#
use strict;
use warnings;
use Term::Animation; 
use Curses;

# creates animation in existing Curses window
initscr();
# newwin coordinates; row/height, column/width, row/starty, column/startx
my $win = newwin(11,45,3,7);
my $anim = Term::Animation->new($win);

$anim->color(1);
$anim->background(my $color = 'white');	# bg is black on default

addstr(10,10, "HELL-0\n");


# ASCII art object 
my @arm = (q{
   __
  / -\
 //
// 
},
q{   
_____
---\ \
     /  
});

$anim->new_entity(
	shape         => \@arm,      
	position      => [1, 1, 2],    
	# row, column, (does not work here?) depth (the higher, the more in bg) 
	callback_args => [1, 0, 0, 1],  
	# default callback routine, object follows vector
	# x horizontal , y vertical movement, z?, anim frame
	default_color => "magenta",
	wrap          => 1 # animation loop
);

#i can type in black window, but how anim? measurement???

# set delay for getch, the higher the number the slower
halfdelay( 21 );

# animation loop, if 0 nothing happens.
while(1) {
# run and display a single animation frame, does not loop. 
$anim->animate();

# use getch to control the frame rate, and get input at the same time. (not a good idea if you are expecting much input) input by filehandle, framerate  by one character typing
my $input = getch();
if($input eq 'q') { last; }
}

#Returns the number of entities in the animation.
my $number_of_entities = $anim->entity_count(1);
addstr ("$number_of_entities");
# cleanly end the animation, to avoid hosing up the user's terminal
$anim->end();










#	my $phrase = "Press q to exit";
#	addstr ($phrase);
#why can't i write into curses
#
#my $number_of_entities = $anim->entity_count();
#addstr ($number_of_entities);
