#!/usr/bin/perl
#
use strict; 
use warnings; 
use Term::Animation; 
use Term::Animation::Entity; 
use Curses; 
use Time::HiRes qw(time); 
use Data::Dumper; 

main(); 

sub add_bat {     

my $shape = q#
/--v--\
   "
me#;
my $mask = q#
MbbybbM
   w  
#;

	my ($anim, $y) = @_;        
	#my $y = 5;

	my $bat = $anim->new_entity(         
	type 		=> 'bat',         
	position 	=> [3, $y, 21],         
	shape 		=> $shape,                     
        color 		=> $mask,         
	callback_args 	=> [1, 1, 0],
	#die_offscreen 	=> 0,         # entity should be killed if it goes off the screen? default 0;
	coll_handler 	=> \&bat_collision,         
	physical 	=> 1,     
	wrap 		=> 1, # animation loop
	#auto_trans 	=> 1 
	# any whitespace before the first non-whitespace in a line should be transparent? maybe good for collision?
	); 
}

sub bat_collision {  
       	my ($bat, $anim) = @_;   
	my $collisions = $bat->collisions();  

	system("bash  was_it_you_who_sent_me_that_communication.sh");

	# return unless defined? $collisions; foreach @collision list at a time;
	foreach my $col_obj (@{$collisions}) {     
	#if ($col_obj->type eq 'animal') {
	
	# Get the current x direction from the callback_args, 0 stops bat;
	my $x_dir = $bat->callback_args->[0];
	
	# Reverse the direction, is that temporality?
	$bat->callback_args->[0] = -$x_dir;   
	# but reverse only once
	#return; }	
	}
}

# can the two subs be combined, like if ($col_obj->type eq 'bat') {
sub animal_collision {  
       	my ($animal, $anim) = @_;   
	my $collisions = $animal->collisions();  
	
	# return unless defined $collisions;   
	foreach my $col_obj (@{$collisions}) {     
	
	# Get the current x direction from the callback_args     
	my $x_dir = $animal->callback_args->[0];     
	
	# Reverse the direction     
	$animal->callback_args->[0] = -$x_dir;   
	} 
} 

sub add_blackbird {

	my @blackbird = (q{
 o"o  
  v 
(  ;)
 '  		
},
q{
 . .  
  v 
(;  ) 		
   i 
});

	my ($anim) = @_;  
	my $animal = $anim->new_entity(
	type 		=> 'animal',         
	shape		=> \@blackbird,
	position	=> [9, 10, 21],	# row, column, depth
     	callback_args   => [1, 0, 0, 1],	
	wrap          	=> 1,		
	physical 	=> 1,
	coll_handler	=> \&animal_collision, 
	#auto_trans 	=> 1 
	);
}

sub add_fly {
	my ($anim) = @_;		
	
	my $fly = $anim->new_entity(
	shape			=> "*",	
	position      		=> [5, 9, 7],	# row / column / depth
	callback 		=> \&random_movement,
	wrap          		=> 1, 
	physical      		=> 1,
	#	collision_handler 	=> \&animal_collision,         
	#auto_trans 		=> 1 
	);
}

sub random_movement {
	my ($fly, $anim) = @_;

	# get the current position of the entity	
	my ($x, $y, $z) = $fly->position();

	# we'll use callback_args to store the last axis we moved in
	my $last_move = $fly->callback_args();
	# if we moved in x last time, move in y this time
	if($last_move eq 'x') {         
		     $fly->callback_args('y');
# move by -1, 0 or 1
$y += int(rand(3)) - 1;      
	} else {         
		$fly->callback_args('x');  
	$x += int(rand(3)) - 1;      
}     

	# return the absolute x,y,z coordinates to move to (return value is always the last calculation performed), this case does not include $frame;
	return ($x, $y, $z);
}

sub add_background {     
	my ($anim, $screen_width, $screen_height) = @_;     
	my $half_width = int($screen_width / 2);     
	my $ground_level = int($screen_height * 0.7);	# what math is this?

		$anim->new_entity(             
			type 		=> 'background',
			shape  		=> ["|\n"x $screen_height],
			position 	=> [$half_width, 0, 21],             
			physical 	=> 1,         
		);     
	} 

sub main {   
	my $anim = Term::Animation->new();   
	$anim->color(1); # red, green, blue, cyan, magenta, yellow, black, white;
	halfdelay(2); # set delay for getch (curses), the higher the number the slower;
	my $paused = 0;	# why 0?
	
while(1) {       
		my $screen_width = $anim->width();       
		my $screen_height = $anim->height();       
		my $half_width = int($screen_width / 2);       
		my $ground_level = int($screen_height * 0.7);       
		
		add_background($anim, $screen_width, $screen_height);       
		my $bat = add_bat($anim, ($ground_level - 1));      
		my $animal = add_blackbird($anim, ($ground_level - 1));  
		my $fly = add_fly($anim);

# animation loop       
	while(1) {           
		my $current_time = time();           # return?
		#addstr ($current_time);
		
		# run and display a single animation frame           
		$anim->animate() unless($paused);           
		
		# use getch to control the frame rate, and get input at the same time;           
			my $input = getch();           
			if($input eq 'q') { quit(); }           
			if($input eq 'r' || $input eq KEY_RESIZE()) { last; }           
			if($input eq 'p') { $paused = !$paused; }       
		}       
		$anim->update_term_size();       
		$anim->remove_all_entities();   
	}   
$anim->end(); 
}

