#!/usr/bin/perl
#
use strict;
use warnings;
use Curses;
use Term::Animation;
use Term::Animation::Entity;	
# callback routine controls position and frame of object; 

main();

sub add_snowflake {
	my ($anim) = @_;	# does that call default callback routine?

	my $snowflake = $anim->new_entity(
	shape         => "*",	
	position      => [7, 9, 5],	# row / column / depth
	callback_args => [1, 0, 0, 0],	# default callback routine
	default_color => 'w', 	
	wrap          => 1, 
	#collision_handler => \&animal_collision,         
	physical      => 1,
	#auto_trans => 1 # any whitespace before the first non-whitespace in a line should be transparent?
	);
}

sub random_movement {     
	my ($snowflake, $anim) = @_;
	my ($x, $y, $z) = $snowflake->position();
	 my $last_move = $snowflake->callback_args();
	     if($last_move eq 'x') {         
		     $snowflake->callback_args('y');


		      $y += int(rand(3)) - 1;      } 
	      else {         
		      $snowflake->callback_args('x');  
		      $x += int(rand(3)) - 1;      }     
	      # return the absolute x,y,z coordinates to move to     
	       return ($x, $y, $z); }


sub main {
	my $anim = Term::Animation->new();	# if constructor is passed no arguments -> fullscreen; accepts no arguments?
	$anim->color(1);
	# set delay for getch;
	halfdelay(3);

	my $snowflake = add_snowflake($anim);


while(1) {	# while loop runs as long condition is true;
	$anim->animate();
	my $input = getch();
	if($input eq 'q') { last; } # does not quit properly
}
}

my $anim->end(); 
 







