#!/bin/bash
#author=cute-count
#purpose=thirst for annihilation

SIZE=1296 #Desired width of .jpg.

#If directory exists, then do not create a new one. 
	if [ -d ~/Images/social/DIRECTORY ]; then      
	echo "Directory exists. New directory will not be created."

#Otherwise, create a new directory.
else      
	echo "Directory does not exist. Creating a new directory .."      
	mkdir -p ~/Images/social/DIRECTORY
fi

#Rename images for img in ~/Images/DSCN29*.JPG;
for img in ~/Images/DSCN29*.JPG;
do 
	mv "$img" "${img/DSCN29/IMAGE}"
done 

#Rename extensions for aesthetics.
for img in ~/Images/*.JPG;
do	
	mv "$img" "${img%.JPG}.jpg" 
done

#Move to new folder ~/Images/social/..;
for img in ~/Images/*.jpg
do 
	mv "$img" ~/Images/social/DIRECTORY/ 
done

#Resize *.jpg and quality only if width is larger than the desired size.	
for img in ~/Images/social/DIRECTORY/*.jpg; 
do     
if [ $(identify -format "%[fx:w]" $img) -gt $SIZE ]; then
	magick "$img" -resize 50% -quality 90 "${img%.jpg}-resized.jpg"
fi
	echo "Optimized: $img"
done

#Rotate a sequence of .jpgs clockwise.
for img in ~/Images/social/DIRECTORY/*{04..10}-resized.jpg; 
do 
	magick "$img" -rotate 90 "${img%.jpg}-rero.jpg"
done 

#Start countdown to remove created directory after 10s.
echo "Purging from rubbish, please wait .."
for i in {10..1}; 
do echo "$i " 
sleep 1 
done

for dir in ~/Images/social/* 
do 
	rm -r "$dir" 
echo "Pouff!"
done
















