#!/usr/bin/perl
#
use strict;
use warnings;

# regular expressions (RegEx), its
# match operator // does not search for /string/ as a ()hole, but to (un)match patterns of indivisible atoms; 
# note that SPACE IS also a character;
# #atomization
# not to be confused with globs *.txt;

# the while loop repeats a block of code as long as a condition is true


# Regex Operator =~, Negated Regex Operator !~ 
#
# metacharacters, the wildcard character (.) $String =~ /t..s/; two characters between them

# backlash is escape character


# the filehandle(<$CAPITAL>) is a gate between the program and files, which opens and closes for file manipulation;

# the die function stops the program in case of fatal errors;
open my $CRASH, '<', 'crash.txt' or die "Cannot open, is jammed! $!\n"; 
open my $INVESTIGATION, '>>', 'crash_investigation.txt' or die "$!\n"; 

while (my $pain = <$CRASH>) {     

if  ($pain =~ /pain[^t]/) # ^ (caret) negates t, to escape "PainTwork"; 
	
{	
	print $INVESTIGATION $pain;
	}
}


close $CRASH;
close $INVESTIGATION;
	

=pod 
print if sex and technology in one sentence. starts with blank space, ends with dot. 


my $_ = "sex technology";
if (\n) {
	print $investigation if
}


 my $word = 'penis';
 
 print $investigation "Found a penis\n\t\a!" if $word =~ /penis/; 


 
 





 sub main {     
	open(FH, $file) or die("File $file not found");          

	while(my $String = <FH>) {         
		if($String =~ /\bs...n\b/)         
		{             
			print "$String \n";         }     
	}     
	close(FH); } main(); =cut # # #how to print sex technology in one line?
