#!/usr/bin/perl
#
use strict;
use warnings;






# Regex Operator =~, Negated Regex Operator !~ 
#
# metacharacters, the wildcard character (.) $String =~ /t..s/; two characters between them

# backlash is escape character


# the filehandle(<$CAPITAL>) is a gate between the program and files, which opens and closes for file manipulation;

open my $CRASH, '<', 'crash.txt' or die "Cannot open, is jammed! $!\n"; 
open my $INVESTIGATION, '>', 'crash_investigation.txt' or die "$!\n"; 

while (my $pain = <$CRASH>) {     

if  ($pain =~ s/pain[^t]/joy/) # ^ (caret) negates t, to escape "PainTwork"; 
	
#here joyful, the f or space is missing, why?
#also caret +M?
{	
	print $INVESTIGATION $pain;
	}
}


close $CRASH;
close $INVESTIGATION;
	

# subsitute pain with joy,  s/pain/joy/
# how to make a break after annotation?


=pod 

# subroutine, print if sex and technology in one sentence. starts with blank space, ends with dot. 


	my $base = "sex, technology";
sub sex_tex {

while ($base = <$CRASH>) {     
	
if (/sex \+ technology) {  # matches sex, space, ONE "word", space, technology;

	print $INVESTIGATION  $base;
}
}

}
sex_tex();




 
 


"Matched: |$`<$&>$'|\n"

 my $word = 'penis';
 
 print $investigation "Found a penis\n\t\a!" if $word =~ /penis/; 




 sub main {     
	open(FH, $file) or die("File $file not found");          

	while(my $String = <FH>) {         
		if($String =~ /\bs...n\b/)         
		{             
			print "$String \n";         }     
	}     
	close(FH); } main(); =cut # # #how to print sex technology in one line?
